#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DrawableStates.Resource", IsApplication=true)]

namespace DrawableStates
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int completed = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int required = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int valid = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int c0 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int c1 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int c2 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int c3 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int c4 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int c5 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int c6 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int c7 = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_completed_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_required_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_valid_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int layout_background = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int completedButton = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int layout = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int requiredButton = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int validButton = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LayoutState = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int LayoutState_completed = 0;
			
			// aapt resource value: 1
			public const int LayoutState_required = 1;
			
			// aapt resource value: 2
			public const int LayoutState_valid = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
